/* THIS FILE WAS GENERATED BY PAYLOAD */
import { NotFoundPage } from '@payloadcms/next/views'
import config from '../../../../payload.config'

type Props = {
  params: Promise<{
    payload: string[]
  }>
  searchParams: Promise<{
    [key: string]: string | string[]
  }>
}

const NotFound = ({ params, searchParams }: Props) =>
  NotFoundPage({ config, params, searchParams })

export default NotFound
