/* THIS FILE WAS GENERATED BY PAYLOAD */
import { RootPage, generateMetadata } from '@payloadcms/next/views'
import config from '@/payload.config'

type Props = {
  params: Promise<{
    payload: string[]
  }>
  searchParams: Promise<{
    [key: string]: string | string[]
  }>
}

export const metadata = ({ params, searchParams }: Props) =>
  generateMetadata({ config, params, searchParams })

const Page = ({ params, searchParams }: Props) =>
  RootPage({ config, params, searchParams })

export default Page
